### ISSUE TITLE
Currently requires PowerShell 5.1 (should be documented in psd1?)

### ISSUE THREAD

**Issue by Jaykul** [markekraus/PSPublishHelper#1]
When I try to run on PowerShell Core I get the error:

> New-Object : Cannot find type [Microsoft.PowerShell.DesiredStateConfiguration.DscResourceInfo]: verify that the assembly containing this type is loaded.

**Comment by markekraus** [comment]
oof... good catch

**Comment by markekraus** [comment]
I added version gating. I want this to work on Core but it looks like DSC resource enumeration wont work on core so there is now a verbose output indicating DSC resrouce modules need to be build on windows PS .
