### ISSUE TITLE
Silently fails when -Output parameter is a relative path

### ISSUE THREAD

**Issue by Jaykul** [markekraus/PSPublishHelper#2]
When I try to `Publish-Module -Output .\output` ... it goes through all the motions but I don't know where it puts the file!

Changing the parameter to `-OutputPath (Convert-Path .\Output)` fixes it -- but I would expect the Convert-Path to be inside the Publish command.

```
> Get-Module -ListAvailable .\Output\Questionmark.Naming\1.1.0\Questionmark.Naming.psd1 | Publish-PSModuleNuget -OutputPath .\Output\ -PassThru -Verbose

VERBOSE: Nuegt found at C:\Users\joel.bennett\Documents\WindowsPowerShell\Tools\nuget.exe
VERBOSE: Using Module from
VERBOSE: ProjectUri:
VERBOSE: Prerelease: Create
VERBOSE: Tags: Naming Conventions Constants Shared NoDependencies
VERBOSE: ReleaseNotes:
VERBOSE: IconUri:
VERBOSE: RequireLicenseAcceptance:
VERBOSE: LicenseUri:
VERBOSE: ProjectUri:
VERBOSE: Prerelease: Create
VERBOSE: Tags: Naming Conventions Constants Shared NoDependencies
VERBOSE: ReleaseNotes:
VERBOSE: IconUri:
VERBOSE: RequireLicenseAcceptance:
VERBOSE: LicenseUri:
VERBOSE: Nuget Pack Output:

```

P.S. For bonus points, typo in verbose message "Nuegt found"

P.P.S. For more bonus points: way too many verbose messages with no information in them. Even when the publish works I get, for instance:
- "using module from" ... without an actual path
- "Nuget Pack Output" ... without the path to that output either

The others, I sort-of expected to be empty in this case -- it might be worth squashing the verbose output if there's nothing to report ...

**Comment by markekraus** [comment]
Fixed the path issue, the spelling error, the missing verbose output, and I changed `nuget pack` to use detailed output and includes that.
