### ISSUE TITLE
Problem with package when dealing with extra files included in module for DSC

### ISSUE THREAD

**Issue by MaxFrost** [markekraus/PSPublishHelper#6]
I am using PSPublishHelper to package a DSC module, and while it does correctly build the module with the classes, per PSScriptAnalyzer, I am to _also_ include an examples folder and Tests folder containing the pester tests for the DSC.

```
# This is my build output before packaging, and how I expect the file structure when I publish
Module
|
- Module.psd1
- Module.psm1 # built, compiled module
| 
---Tests
   - Module_class1.tests.ps1
---Examples
   - Module_class1.ps1 # DSC example file
```

The issue is when using PSPublishHelper, passing in the PSD1 as the build point, the extra files in the tests and examples folder are getting copied into the root, then the whole package is zipped up into the nuget. Output looks like this within the nuget

```
Module
|
- Module.psd1
- Module.psm1
- Module_class1.tests.ps1
- Module_class1.ps1
| 
---Tests
   - Module_class1.tests.ps1
---Examples
   - Module_class1.ps1 # DSC example file
```

To be fair, it's _working_, but only because those extra files aren't imported, but it is cluttering up the root and clearly isn't intentional. I'm not seeing any options for `Publish-PSModuleNuget` to say "package but don't process these files"

**Comment by markekraus** [comment]
PSPublishHelper has an opinionated folder structure. This is by design. I would recommend moving those folders out of the opinionated structure.

**Comment by MaxFrost** [comment]
I don't know what you mean by that. Do you mean there should be *no* subfolders? 

I am _intending_ to ship these two subfolders with the module. They are part of the documentation of this module.

The problem appears to be in Copy-PSModule, lines 28 OR line 36.

Line 28, you are recursing the source tree. If you find a container, you then copy+recurse that to root. However, the get-childitem recurse is still going, and copies the item a second time to the root.

OR 

line 36, if you're not wanting to copy subdirectires and copy files flat, you should be setting Container to $false, and not copy containers, but continue the recurse.
